# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/next"

[context.production.environment]
  NODE_VERSION = "18"
  NEXT_PRIVATE_TARGET = "server"
